In [5]:
import numpy as np

In [7]:
import pandas as pd

In [8]:
movies= pd.read_csv('tmdb_5000_movies.csv')

In [10]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [9]:
credits= pd.read_csv('tmdb_5000_credits.csv')

In [12]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [11]:
movies= movies.merge(credits, on='title')

In [14]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [12]:
movies= movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [16]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [19]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [20]:
movies.duplicated().sum()

np.int64(0)

In [21]:
movies.drop_duplicates()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [14]:
#Genres here is basically a string of list of dictionaries so first we need to convert it to List
#so we convert the string to a list using the ast and ast's literal_eval
#append basically adds to end of list

import ast

In [15]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres']=movies['genres'].apply(convert)

In [17]:
movies['keywords']=movies['keywords'].apply(convert)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!= 3:
         L.append(i['name'])
         counter+=1
        else:
            break
    return L

In [19]:
movies['cast']= movies['cast'].apply(convert3)

In [68]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
#indentation of break is important, if break used exactly below if it checks if condition, not matches so break with first element.
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
         L.append(i['name'])
         break
    return L

In [21]:
movies['crew']= movies['crew'].apply(fetch_director)

In [91]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [22]:
#lambda is anonymous function for just a line call and split basically separates into words and individual lists per row.
movies['overview']= movies['overview'].apply(lambda x:x.split())

In [98]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [23]:
#gives no space to those with space in between
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [102]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [24]:
movies['tags']= movies['overview']+ movies['genres'] +movies['keywords']+ movies['cast']+ movies['crew']

In [106]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [25]:
new_df= movies[['movie_id','title','tags']]

In [109]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [110]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [26]:
#converts list of strings into strings themselves per row
new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13352\938549947.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

In [114]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [116]:
new_df['tag'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [27]:
new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13352\2543325826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x: x.lower())

In [119]:
new_df.head()

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [28]:
#choose from ishuenv kernel in top right corner
#choose 5000 most common words so max_features=5000
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000, stop_words='english')

In [29]:
#scipy sparse matrix by default, so convert it to array 
vectors= cv.fit_transform(new_df['tags']).toarray()

In [34]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [35]:
#apply stemming to make similar words all the same e.g. loving, lovely, lovable to 'love' so all those are treated as the same common word
!pip install nltk

Collecting nltk
  Downloading nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting click (from nltk)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: joblib in c:\users\administrator\desktop\movies_rec\ishuenv\lib\site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.5.15-cp312-cp312-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     ---------------------------------------- 42.0/42.0 kB 2.1 MB/s eta 0:00:00
Collecting tqdm (from nltk)
  Downloading tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ------- -------------------------------- 10.2/57.6 kB ? eta -:--:--
     ------- -------------------------------- 10.2/57.6 kB ? eta -:--:--
     ------- -------------------------------- 10.2/57.6 kB ? eta -:--:--
     -------------------- ----------------- 30.7/57.6 kB 163.8 kB/s eta 0:00:01
     -------------------------------------- 57.6/57.6 kB 253.0 kB/s eta 0:00:00
Requirement already satisfied: colorama in c:\users\administrator\desktop\movies_rec\ishuenv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
    --------------------------------------- 0.0/1.5 MB 187.9 kB/s eta 0:00:08
   - -------------------------------------- 0.0/1.5 MB 178.6 kB/s eta 0:00:09
   - -------------------------------------- 0.1/1.5 MB 233.8 kB/s eta 0:00:07
   - -------------------------------------- 0.1/1.5 MB 233.8 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/1.5 MB 218.5 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/1.5 MB 218.5 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/1.5 MB 218.5 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/1.5 MB 218.5 kB/s eta 0:00:07
   -- ------------------------------------- 0.1/1.5 MB 169.3 kB/s eta 0:00:09
   -- ------------------------------------- 0.1/1.5 MB 169.3 kB/s eta 0:00:09
   -- ------------------------------------- 0.1/1.5 MB 169.3 kB/s eta 0:00:09
   -- ------------------------------------- 0.1/1.5 MB 169.3 kB/s eta 0:00:09
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.1/1.5 MB 145.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.1/1.5 MB 103.0 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 103.0 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 103.0 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 103.0 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 103.0 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 103.0 kB/s eta 0:00:14
   --- ------------------------------------ 0.1/1.5 MB 95.8 kB/s eta 0:00:15
   --- ------------------------------------ 0.1/1.5 MB 95.8 kB/s eta 0:00:15
   --- ------------------------------------ 0.1/1.5 MB 95.8 kB/s eta 0:00:15
   --- ------------------------------------ 0.1/1.5 MB 95.8 kB/s eta 0:00:15
   ---- ----------------------------------- 0.2/1.5 MB 97.3 kB/s eta 0:00:14
   ---- ----------------------------------- 0.2/1.5 MB 97.3 kB/s eta 0:00:14
   ---- ----------------------------------- 0.2/1.5 MB 97.3 kB/s eta 0:00:14
   ---- ----------------------------------- 0.2/1.5 MB 96.2 kB/s eta 0:00:14
   ---- ----------------------------------- 0.2/1.5 MB 96.2 kB/s eta 0:00:14
   ----- ---------------------------------- 0.2/1.5 MB 101.7 kB/s eta 0:00:13
   ----- ---------------------------------- 0.2/1.5 MB 101.7 kB/s eta 0:00:13
   ----- ---------------------------------- 0.2/1.5 MB 101.7 kB/s eta 0:00:13
   ----- ---------------------------------- 0.2/1.5 MB 100.4 kB/s eta 0:00:14
   ----- ---------------------------------- 0.2/1.5 MB 100.4 kB/s eta 0:00:14
   ----- ---------------------------------- 0.2/1.5 MB 105.9 kB/s eta 0:00:13
   ----- ---------------------------------- 0.2/1.5 MB 105.9 kB/s eta 0:00:13
   ------ --------------------------------- 0.2/1.5 MB 110.8 kB/s eta 0:00:12
   ------ --------------------------------- 0.2/1.5 MB 110.8 kB/s eta 0:00:12
   ------ --------------------------------- 0.2/1.5 MB 110.8 kB/s eta 0:00:12
   ------- -------------------------------- 0.3/1.5 MB 113.0 kB/s eta 0:00:12
   ------- -------------------------------- 0.3/1.5 MB 118.0 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 118.0 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 118.4 kB/s eta 0:00:11
   ------- -------------------------------- 0.3/1.5 MB 118.4 kB/s eta 0:00:11
   -------- ------------------------------- 0.3/1.5 MB 123.7 kB/s eta 0:00:10
   -------- ------------------------------- 0.3/1.5 MB 124.6 kB/s eta 0:00:10
   --------- ------------------------------ 0.3/1.5 MB 129.5 kB/s eta 0:00:09
   --------- ------------------------------ 0.3/1.5 MB 129.5 kB/s eta 0:00:09
   --------- ------------------------------ 0.4/1.5 MB 133.4 kB/s eta 0:00:09
   ---------- ----------------------------- 0.4/1.5 MB 134.8 kB/s eta 0:00:09
   ---------- ----------------------------- 0.4/1.5 MB 134.8 kB/s eta 0:00:09
   ---------- ----------------------------- 0.4/1.5 MB 138.4 kB/s eta 0:00:09
   ---------- ----------------------------- 0.4/1.5 MB 138.9 kB/s eta 0:00:08
   ----------- ---------------------------- 0.4/1.5 MB 143.7 kB/s eta 0:00:08
   ----------- ---------------------------- 0.5/1.5 MB 148.3 kB/s eta 0:00:08
   ------------ --------------------------- 0.5/1.5 MB 148.7 kB/s eta 0:00:08
   ------------ --------------------------- 0.5/1.5 MB 153.0 kB/s eta 0:00:07
   ------------ --------------------------- 0.5/1.5 MB 153.0 kB/s eta 0:00:07
   ------------- -------------------------- 0.5/1.5 MB 158.2 kB/s eta 0:00:07
   ------------- -------------------------- 0.5/1.5 MB 158.2 kB/s eta 0:00:07
   -------------- ------------------------- 0.5/1.5 MB 161.5 kB/s eta 0:00:07
   -------------- ------------------------- 0.5/1.5 MB 161.5 kB/s eta 0:00:07
   -------------- ------------------------- 0.6/1.5 MB 165.4 kB/s eta 0:00:06
   -------------- ------------------------- 0.6/1.5 MB 165.4 kB/s eta 0:00:06
   -------------- ------------------------- 0.6/1.5 MB 165.4 kB/s eta 0:00:06
   -------------- ------------------------- 0.6/1.5 MB 165.4 kB/s eta 0:00:06
   --------------- ------------------------ 0.6/1.5 MB 160.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.6/1.5 MB 163.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.6/1.5 MB 163.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.6/1.5 MB 163.9 kB/s eta 0:00:06
   --------------- ------------------------ 0.6/1.5 MB 163.9 kB/s eta 0:00:06
   ---------------- ----------------------- 0.6/1.5 MB 161.1 kB/s eta 0:00:06
   ---------------- ----------------------- 0.6/1.5 MB 161.1 kB/s eta 0:00:06
   ---------------- ----------------------- 0.6/1.5 MB 161.1 kB/s eta 0:00:06
   ---------------- ----------------------- 0.6/1.5 MB 158.6 kB/s eta 0:00:06
   ---------------- ----------------------- 0.6/1.5 MB 158.6 kB/s eta 0:00:06
   ---------------- ----------------------- 0.6/1.5 MB 158.6 kB/s eta 0:00:06
   ---------------- ----------------------- 0.6/1.5 MB 158.6 kB/s eta 0:00:06
   ----------------- ---------------------- 0.6/1.5 MB 156.3 kB/s eta 0:00:06
   ----------------- ---------------------- 0.6/1.5 MB 156.3 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 153.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 153.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 153.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 153.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 153.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 153.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ----------------- ---------------------- 0.7/1.5 MB 149.5 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 142.1 kB/s eta 0:00:06
   ------------------ --------------------- 0.7/1.5 MB 129.9 kB/s eta 0:00:07
   ------------------ --------------------- 0.7/1.5 MB 129.9 kB/s eta 0:00:07
   ------------------ --------------------- 0.7/1.5 MB 129.9 kB/s eta 0:00:07
   ------------------ --------------------- 0.7/1.5 MB 129.9 kB/s eta 0:00:07
   ------------------ --------------------- 0.7/1.5 MB 129.9 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 128.9 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 128.9 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 128.9 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 128.9 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 128.9 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 124.7 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 124.7 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 124.7 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 124.7 kB/s eta 0:00:07
   ------------------- -------------------- 0.7/1.5 MB 124.7 kB/s eta 0:00:07
   -------------------- ------------------- 0.8/1.5 MB 123.9 kB/s eta 0:00:07
   -------------------- ------------------- 0.8/1.5 MB 123.9 kB/s eta 0:00:07
   -------------------- ------------------- 0.8/1.5 MB 123.9 kB/s eta 0:00:07
   -------------------- ------------------- 0.8/1.5 MB 123.9 kB/s eta 0:00:07
   -------------------- ------------------- 0.8/1.5 MB 123.5 kB/s eta 0:00:06
   -------------------- ------------------- 0.8/1.5 MB 123.5 kB/s eta 0:00:06
   -------------------- ------------------- 0.8/1.5 MB 123.5 kB/s eta 0:00:06
   -------------------- ------------------- 0.8/1.5 MB 122.1 kB/s eta 0:00:06
   -------------------- ------------------- 0.8/1.5 MB 122.1 kB/s eta 0:00:06
   --------------------- ------------------ 0.8/1.5 MB 123.2 kB/s eta 0:00:06
   --------------------- ------------------ 0.8/1.5 MB 123.2 kB/s eta 0:00:06
   --------------------- ------------------ 0.8/1.5 MB 123.2 kB/s eta 0:00:06
   --------------------- ------------------ 0.8/1.5 MB 122.4 kB/s eta 0:00:06
   ---------------------- ----------------- 0.8/1.5 MB 124.3 kB/s eta 0:00:06
   ---------------------- ----------------- 0.8/1.5 MB 124.3 kB/s eta 0:00:06
   ---------------------- ----------------- 0.8/1.5 MB 124.4 kB/s eta 0:00:06
   ---------------------- ----------------- 0.8/1.5 MB 124.4 kB/s eta 0:00:06
   ---------------------- ----------------- 0.8/1.5 MB 124.4 kB/s eta 0:00:06
   ----------------------- ---------------- 0.9/1.5 MB 124.8 kB/s eta 0:00:06
   ----------------------- ---------------- 0.9/1.5 MB 124.8 kB/s eta 0:00:06
   ----------------------- ---------------- 0.9/1.5 MB 124.3 kB/s eta 0:00:06
   ----------------------- ---------------- 0.9/1.5 MB 124.3 kB/s eta 0:00:06
   ----------------------- ---------------- 0.9/1.5 MB 125.6 kB/s eta 0:00:05
   ----------------------- ---------------- 0.9/1.5 MB 125.6 kB/s eta 0:00:05
   ----------------------- ---------------- 0.9/1.5 MB 125.6 kB/s eta 0:00:05
   ----------------------- ---------------- 0.9/1.5 MB 125.6 kB/s eta 0:00:05
   ------------------------ --------------- 0.9/1.5 MB 124.9 kB/s eta 0:00:05
   ------------------------ --------------- 0.9/1.5 MB 124.9 kB/s eta 0:00:05
   ------------------------ --------------- 0.9/1.5 MB 125.5 kB/s eta 0:00:05
   ------------------------ --------------- 0.9/1.5 MB 125.5 kB/s eta 0:00:05
   ------------------------ --------------- 0.9/1.5 MB 125.5 kB/s eta 0:00:05
   ------------------------ --------------- 0.9/1.5 MB 125.5 kB/s eta 0:00:05
   ------------------------- -------------- 1.0/1.5 MB 124.8 kB/s eta 0:00:05
   ------------------------- -------------- 1.0/1.5 MB 124.8 kB/s eta 0:00:05
   ------------------------- -------------- 1.0/1.5 MB 124.8 kB/s eta 0:00:05
   ------------------------- -------------- 1.0/1.5 MB 123.9 kB/s eta 0:00:05
   ------------------------- -------------- 1.0/1.5 MB 123.9 kB/s eta 0:00:05
   ------------------------- -------------- 1.0/1.5 MB 123.9 kB/s eta 0:00:05
   ------------------------- -------------- 1.0/1.5 MB 123.9 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 123.5 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 123.5 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 123.5 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 124.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 124.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 124.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 124.2 kB/s eta 0:00:05
   -------------------------- ------------- 1.0/1.5 MB 122.1 kB/s eta 0:00:05
   --------------------------- ------------ 1.0/1.5 MB 123.9 kB/s eta 0:00:04
   --------------------------- ------------ 1.0/1.5 MB 123.9 kB/s eta 0:00:04
   --------------------------- ------------ 1.0/1.5 MB 123.9 kB/s eta 0:00:04
   --------------------------- ------------ 1.0/1.5 MB 123.9 kB/s eta 0:00:04
   --------------------------- ------------ 1.0/1.5 MB 122.8 kB/s eta 0:00:04
   --------------------------- ------------ 1.0/1.5 MB 122.8 kB/s eta 0:00:04
   ---------------------------- ----------- 1.1/1.5 MB 123.4 kB/s eta 0:00:04
   ---------------------------- ----------- 1.1/1.5 MB 123.4 kB/s eta 0:00:04
   ---------------------------- ----------- 1.1/1.5 MB 123.4 kB/s eta 0:00:04
   ---------------------------- ----------- 1.1/1.5 MB 122.8 kB/s eta 0:00:04
   ---------------------------- ----------- 1.1/1.5 MB 122.8 kB/s eta 0:00:04
   ---------------------------- ----------- 1.1/1.5 MB 122.8 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 123.0 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 123.0 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 123.0 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 123.0 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 123.0 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 123.0 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 121.6 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 121.6 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 121.6 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 121.6 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 120.1 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 120.1 kB/s eta 0:00:04
   ----------------------------- ---------- 1.1/1.5 MB 120.1 kB/s eta 0:00:04
   ------------------------------ --------- 1.1/1.5 MB 120.4 kB/s eta 0:00:04
   ------------------------------ --------- 1.1/1.5 MB 120.4 kB/s eta 0:00:04
   ------------------------------ --------- 1.1/1.5 MB 120.4 kB/s eta 0:00:04
   ------------------------------ --------- 1.1/1.5 MB 120.4 kB/s eta 0:00:04
   ------------------------------ --------- 1.2/1.5 MB 119.5 kB/s eta 0:00:03
   ------------------------------ --------- 1.2/1.5 MB 119.5 kB/s eta 0:00:03
   ------------------------------- -------- 1.2/1.5 MB 120.5 kB/s eta 0:00:03
   ------------------------------- -------- 1.2/1.5 MB 120.5 kB/s eta 0:00:03
   ------------------------------- -------- 1.2/1.5 MB 121.2 kB/s eta 0:00:03
   ------------------------------- -------- 1.2/1.5 MB 121.2 kB/s eta 0:00:03
   ------------------------------- -------- 1.2/1.5 MB 120.9 kB/s eta 0:00:03
   ------------------------------- -------- 1.2/1.5 MB 120.9 kB/s eta 0:00:03
   -------------------------------- ------- 1.2/1.5 MB 122.1 kB/s eta 0:00:03
   -------------------------------- ------- 1.2/1.5 MB 122.1 kB/s eta 0:00:03
   -------------------------------- ------- 1.2/1.5 MB 121.9 kB/s eta 0:00:03
   --------------------------------- ------ 1.3/1.5 MB 122.8 kB/s eta 0:00:03
   --------------------------------- ------ 1.3/1.5 MB 122.8 kB/s eta 0:00:03
   --------------------------------- ------ 1.3/1.5 MB 124.1 kB/s eta 0:00:02
   --------------------------------- ------ 1.3/1.5 MB 124.1 kB/s eta 0:00:02
   ---------------------------------- ----- 1.3/1.5 MB 123.9 kB/s eta 0:00:02
   ---------------------------------- ----- 1.3/1.5 MB 125.2 kB/s eta 0:00:02
   ----------------------------------- ---- 1.3/1.5 MB 126.8 kB/s eta 0:00:02
   ------------------------------------ --- 1.4/1.5 MB 128.0 kB/s eta 0:00:02
   ------------------------------------ --- 1.4/1.5 MB 128.0 kB/s eta 0:00:02
   ------------------------------------- -- 1.4/1.5 MB 130.7 kB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 132.9 kB/s eta 0:00:01
   ---------------------------------------  1.5/1.5 MB 133.6 kB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 131.4 kB/s eta 0:00:00
Downloading regex-2024.5.15-cp312-cp312-win_amd64.whl (268 kB)
   ---------------------------------------- 0.0/268.5 kB ? eta -:--:--
   ------------------------ --------------- 163.8/268.5 kB 2.4 MB/s eta 0:00:01
   ---------------------------- ----------- 194.6/268.5 kB 1.2 MB/s eta 0:00:01
   -------------------------------- ------- 215.0/268.5 kB 1.0 MB/s eta 0:00:01
   ---------------------------------- --- 245.8/268.5 kB 684.7 kB/s eta 0:00:01
   -------------------------------------  266.2/268.5 kB 629.0 kB/s eta 0:00:01
   -------------------------------------- 268.5/268.5 kB 446.0 kB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)

In [36]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [37]:


def stem(text):
    y= []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [39]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13352\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
#4806 by 4806 since each movie with every movie- 
similarity= cosine_similarity(vectors)

In [44]:
similarity[0]

array([1.        , 0.08980265, 0.05986843, ..., 0.02457366, 0.02777778,
       0.        ])

In [48]:
#only the values but without indices loses the positions so we use enumerate with sort
#similarity[0] means the movie, x[1] means with respect to the second column sorting should be done which is cosine similarities
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(539, np.float64(0.25724787771376323)),
 (1192, np.float64(0.2545875386086578)),
 (260, np.float64(0.24759378423606915)),
 (507, np.float64(0.2472066162365221)),
 (1214, np.float64(0.24595492912420727))]

In [50]:
#new_df['title']==movie finds from new_df the object of the movie and then this object put into new_df[movie] and from here the index[0] or 
#movie_id is extracted
def recommend(movie):
  movie_index= new_df[new_df['title']== movie].index[0]
  distances= similarity[movie_index] #finds the similarity cosine list of the given movie
  movies_list= sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]  #distances = similarity[movie_index] so it sorts the similarity list of that movie

  for i in movies_list:
      print(new_df.iloc[i[0]].title)   #i[0] gives the first column of movies_list which is the movie ids
#iloc gives the exact position

In [51]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Ender's Game
Independence Day
Aliens vs Predator: Requiem

In [52]:
recommend('Batman')

Batman
Batman & Robin
The Dark Knight Rises
Batman Begins
Batman Returns